baseurl: ''
description: >
  engineering, programming, systems, mathematics, philosophy
email: matthew@eudaimonia.io
github_username:  spacez320
title: Matthew's Writings
twitter_username: spacez320
url: 'https://eudaimonia.io'

# Build settings.
exclude: ['Dockerfile', 'Gemfile*', 'README']
markdown: kramdown

# Serve settings.
force_polling: true
host: 0.0.0.0
port: 8000

# Front Matter settings.
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
