# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: '' # the subpath of your site, e.g. /blog
description: > # this means to ignore newlines until 'baseurl:'
  engineering, programming, systems, mathematics, philosophy
email: matthew@eudaimonia.io
github_username:  spacez320
title: Matthew's Writings
twitter_username: spacez320
url: 'https://eudaimonia.io' # the base hostname & protocol for your site

# Build settings
exclude: ['Gemfile*', 'README', 'Vagrantfile']
markdown: kramdown

# Serve settings
force_polling: true
host: 0.0.0.0
port: 8000

# Front Matter settings
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
